quark/base/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.base.views import HomePageView
from quark.base.views import ITToolsView
from quark.base.views import OfficerContactExportView
from quark.base.views import OfficersListView
from quark.base.views import OfficerPortalView
from quark.base.views import ProcrastinationView


urlpatterns = patterns(
    '',
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^officers/$', OfficersListView.as_view(), name='officers'),
    url(r'^officers/contacts/$', OfficerContactExportView.as_view(),
        name='officer-contacts'),
    # TODO(sjdemartini): Restrict the pages below with proper permissions
    url(r'^officer-portal/$', OfficerPortalView.as_view(),
        name='officer-portal'),
    url(r'^it-tools/$', ITToolsView.as_view(), name='it-tools'),
    url(r'^procrastination/$', ProcrastinationView.as_view(),
        name='procrastination'),
    # TODO(sjdemartini): Add a Members database view
)

quark/courses/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.courses.views import CourseDetailView
from quark.courses.views import CourseListView
from quark.courses.views import CourseDepartmentListView
from quark.courses.views import CourseCreateView
from quark.courses.views import CourseEditView
from quark.courses.views import CourseDeleteView
from quark.courses.views import InstructorCreateView
from quark.courses.views import InstructorDepartmentListView
from quark.courses.views import InstructorDeleteView
from quark.courses.views import InstructorDetailView
from quark.courses.views import InstructorEditView
from quark.courses.views import InstructorListView
from quark.courses.views import listCourses


urlpatterns = patterns(
    '',
    url(r'^list', listCourses, name='search'),
    url(r'^$', CourseDepartmentListView.as_view(),
        name='course-department-list'),
    url(r'^(?P<dept_slug>(?!instructors)[A-Za-z-]+)/$',
        CourseListView.as_view(), name='course-list'),
    url(r'^(?P<dept_slug>(?!instructors)[A-Za-z-]+)/'
        '(?P<course_num>[A-Za-z0-9w-]+)/$',
        CourseDetailView.as_view(), name='course-detail'),
    url(r'^add$', CourseCreateView.as_view(),
        name='add-course'),
    url(r'^(?P<cous_pk>[0-9]+)/edit/$', CourseEditView.as_view(),
        name='edit-course'),
    url(r'^(?P<cous_pk>[0-9]+)/delete/$',
        CourseDeleteView.as_view(), name='delete-course'),
    url(r'^instructors/$', InstructorDepartmentListView.as_view(),
        name='instructor-department-list'),
    url(r'^instructors/add/$', InstructorCreateView.as_view(),
        name='add-instructor'),
    url(r'^instructors/(?P<dept_slug>[A-Za-z-]+)/$',
        InstructorListView.as_view(), name='instructor-list'),
    url(r'^instructors/(?P<inst_pk>[0-9]+)/$',
        InstructorDetailView.as_view(), name='instructor-detail'),
    url(r'^instructors/(?P<inst_pk>[0-9]+)/edit/$',
        InstructorEditView.as_view(), name='edit-instructor'),
    url(r'^instructors/(?P<inst_pk>[0-9]+)/delete/$',
        InstructorDeleteView.as_view(), name='delete-instructor'),
)

quark/events/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.emailer.views import EventEmailerView
from quark.events.views import AllTimeLeaderboardListView
from quark.events.views import attendance_delete
from quark.events.views import attendance_search
from quark.events.views import attendance_submit
from quark.events.views import AttendanceRecordView
from quark.events.views import EventBuilderView
from quark.events.views import EventCancelView
from quark.events.views import EventCreateView
from quark.events.views import EventDetailView
from quark.events.views import EventListView
from quark.events.views import EventSignUpView
from quark.events.views import event_revive
from quark.events.views import event_unsignup
from quark.events.views import EventUpdateView
from quark.events.views import ical
from quark.events.views import IndividualAttendanceListView
from quark.events.views import LeaderboardListView

urlpatterns = patterns(
    '',
    url(r'^$', EventListView.as_view(), name='list'),
    url(r'^builder/$', EventBuilderView.as_view(), name='builder'),
    url(r'^add/$', EventCreateView.as_view(), name='add'),
    url(r'^(?P<event_pk>\d+)/$', EventDetailView.as_view(),
        name='detail'),
    url(r'^(?P<event_pk>\d+)/edit/$', EventUpdateView.as_view(), name='edit'),
    url(r'^(?P<event_pk>\d+)/cancel/$', EventCancelView.as_view(),
        name='cancel'),
    url(r'^(?P<event_pk>\d+)/revive/$', event_revive,
        name='revive'),
    url(r'^(?P<event_pk>\d+)/signup/$', EventSignUpView.as_view(),
        name='signup'),
    url(r'^(?P<event_pk>\d+)/unsignup/$', event_unsignup,
        name='unsignup'),
    url(r'^(?P<event_pk>\d+)/attendance/$', AttendanceRecordView.as_view(),
        name='attendance'),
    url(r'^(?P<event_pk>\d+)/email/$', EventEmailerView.as_view(),
        name='email'),
    url(r'^attendance/delete/$', attendance_delete, name='attendance-delete'),
    url(r'^attendance/search/$', attendance_search, name='attendance-search'),
    url(r'^attendance/submit/$', attendance_submit, name='attendance-submit'),
    url(r'^user/(?P<username>[a-zA-Z0-9._-]+)/$',
        IndividualAttendanceListView.as_view(), name='individual-attendance'),
    url(r'^calendar/$', EventListView.as_view(show_all=True,
        template_name='events/calendar.html'), name='calendar'),
    url(r'^leaderboard/$', LeaderboardListView.as_view(), name='leaderboard'),
    url(r'^leaderboard/all-time/$',
        AllTimeLeaderboardListView.as_view(), name='all-time-leaderboard'),
    url(r'^events.ics$', ical, name='ical'),
    url(r'^(?P<event_pk>\d+)/event.ics$', ical, name='event-ical'),
)

quark/exams/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.exams.views import ExamDeleteView
from quark.exams.views import ExamDownloadView
from quark.exams.views import ExamEditView
from quark.exams.views import ExamFlagCreateView
from quark.exams.views import ExamFlagResolveView
from quark.exams.views import ExamReviewListView
from quark.exams.views import ExamUploadView


urlpatterns = patterns(
    '',
    url(r'^review/$', ExamReviewListView.as_view(), name='review'),
    url(r'^upload/$', ExamUploadView.as_view(), name='upload'),
    url(r'^(?P<exam_pk>\d+)/edit/$', ExamEditView.as_view(), name='edit'),
    url(r'^(?P<exam_pk>\d+)/delete/$', ExamDeleteView.as_view(), name='delete'),
    url(r'^(?P<exam_pk>\d+)/download/$', ExamDownloadView.as_view(),
        name='download'),
    url(r'^(?P<exam_pk>\d+)/flag/$', ExamFlagCreateView.as_view(), name='flag'),
    url(r'^(?P<exam_pk>\d+)/flag/(?P<flag_pk>\d+)/$',
        ExamFlagResolveView.as_view(), name='flag-resolve'),
)

quark/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^', include('quark.base.urls',
                      app_name='base')),
    url(r'^accounts/', include('quark.accounts.urls',
                               app_name='accounts',
                               namespace='accounts')),
    url(r'^achievements/', include('quark.achievements.urls',
                                   app_name='achievements',
                                   namespace='achievements')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^alumni/', include('quark.alumni.urls',
                             app_name='alumni',
                             namespace='alumni')),
    url(r'^candidates/', include('quark.candidates.urls',
                                 app_name='candidates',
                                 namespace='candidates')),
    url(r'^courses/', include('quark.courses.urls',
                              app_name='courses',
                              namespace='courses')),
    url(r'^email/', include('quark.emailer.urls',
                            app_name='emailer',
                            namespace='emailer')),
    url(r'^events/', include('quark.events.urls',
                             app_name='events',
                             namespace='events')),
    url(r'^exams/', include('quark.exams.urls',
                            app_name='exams',
                            namespace='exams')),
    url(r'^houses/', include('quark.houses.urls',
                             app_name='houses',
                             namespace='houses')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^industry/', include('quark.companies.urls',
                               app_name='companies',
                               namespace='companies')),
    url(r'^mailing-lists/', include('quark.mailing_lists.urls',
                                    app_name='mailing_lists',
                                    namespace='mailing-lists')),
    url(r'^minutes/', include('quark.minutes.urls',
                              app_name='minutes',
                              namespace='minutes')),
    url(r'^newsreel/', include('quark.newsreel.urls',
                               app_name='newsreel',
                               namespace='newsreel')),
    url(r'^notifications/', include('quark.notifications.urls',
                                    app_name='notifications',
                                    namespace='notifications')),
    url(r'^past-presidents/', include('quark.past_presidents.urls',
                                      app_name='past_presidents',
                                      namespace='past-presidents')),
    url(r'^profile/', include('quark.user_profiles.urls',
                              app_name='user_profiles',
                              namespace='user-profiles')),
    url(r'^project-reports/', include('quark.project_reports.urls',
                                      app_name='project_reports',
                                      namespace='project-reports')),
    url(r'^quote-board/', include('quark.quote_board.urls',
                                  app_name='quote_board',
                                  namespace='quote-board')),
    url(r'^resumes/', include('quark.resumes.urls',
                              app_name='resumes',
                              namespace='resumes')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^videos/', include('quark.videos.urls',
                             app_name='videos',
                             namespace='videos')),
    url(r'^vote/', include('quark.vote.urls',
                           app_name='vote',
                           namespace='vote')),
)

# Add flatpages URLs
urlpatterns += patterns(
    'django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^about/contact/$', 'flatpage', {'url': '/about/contact/'},
        name='contact'),
    url(r'^about/eligibility/$', 'flatpage', {'url': '/about/eligibility/'},
        name='eligibility'),
    url(r'^people/committees/$', 'flatpage', {'url': '/people/committees/'},
        name='committees'),
    url(r'^student-resources/$', 'flatpage', {'url': '/student-resources/'},
        name='student-resources'),
    url(r'^resume-critique/$', 'flatpage', {'url': '/resume-critique/'},
        name='resume-critique'),
    url(r'^mock-interviews/$', 'flatpage', {'url': '/mock-interviews/'},
        name='mock-interviews'),
    url(r'^partnership_program/$', 'flatpage', {'url': '/partnership_program/'},
        name='partnership_program'),
)

# Handle page redirects
urlpatterns += patterns(
    '',
    url(r'^indrel/$', RedirectView.as_view(pattern_name='industry')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quark/vote/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.vote.views import PollCreateView
from quark.vote.views import PollListView
from quark.vote.views import ResultsView
from quark.vote.views import VoteCreateView


urlpatterns = patterns(
    '',
    url(r'^$', PollListView.as_view(), name='list'),
    url(r'^create/$', PollCreateView.as_view(), name='create'),
    url(r'^vote/(?P<poll_pk>\d+)/$', VoteCreateView.as_view(), name='vote'),
    url(r'^result/(?P<poll_pk>\d+)/$', ResultsView.as_view(), name='result')
)

quark/base/forms.py
from chosen import forms as chosen_forms

from quark.base.models import Term


class ChosenTermMixin(object):
    """Form mixin to use Chosen for the "term" form field.

    This mixin is useful because the queryset is commonly used for term
    selection in a form, where all terms up to and including the current term
    are listed in reverse order.
    """
    def __init__(self, *args, **kwargs):
        super(ChosenTermMixin, self).__init__(*args, **kwargs)

        # For fields which reference a QuerySet that must be evaluated (i.e,
        # hits the database and isn't "lazy"), create fields in the __init__ to
        # avoid database errors in Django's test runner
        self.fields['term'] = chosen_forms.ChosenModelChoiceField(
            queryset=Term.objects.get_terms(
                include_future=False, include_summer=True, reverse=True),
            initial=Term.objects.get_current_term())

quark/base/templates/base/it_tools.html
{% extends 'base.html' %}

{% block title %}IT Tools{% endblock title %}

{% block intro %}
<h1>IT Tools</h1>
{% endblock intro %}

{% block content %}
<ul class="tools">
  <li><a href="{% url 'admin:index' %}">Django Admin</a></li>
  <li><a href="/gerrit/">Gerrit Code Review</a></li>
  <li><a href="/buildbot/">Buildbot</a> (Automated Build Testing)</li>
  <li><a href="/trac/">Trac</a></li>
  <li><a href="/phpmyadmin/">phpMyAdmin</a> (MySQL database helper)</li>
  <li><a href="/phpldapadmin/">phpLDAPadmin</a> (User database)</li>
  <li><a href="/~christandiono/stats_quark/">GIT stats</a></li>
</ul>
{% endblock content %}

quark/base/templates/base/officer_portal.html
{% extends 'base.html' %}

{% load settings_values %}

{% block title %}Officer Portal{% endblock title %}

{% block intro %}
<h1>Officer Portal</h1>
{% endblock intro %}

{% block content %}
<h2>Officer Resources</h2>
<ul>
  <li><a href="/officer/library/">Officer Wiki</a></li>
  <li><a href="/officer/library/Officer_Meeting_Agenda">Officer Meeting Agenda</a></li>
  {% if perms.project_reports.view_project_reports %}
  <li><a href="{% url 'project-reports:list' %}">Project Reports</a></li>
  {% endif %}
  {% if perms.base.view_officer_contacts %}
  <li><a href="{% url 'officer-contacts' %}">Officer Contact Info (import into Gmail)</a></li>
  {% endif %}
  <li><a href="https://tbpcaa.slack.com/" target="_blank">Officer Slack Chat</a></li>
  {% if perms.minutes.view_minutes %}
  <li><a href="{% url 'minutes:list' %}">Meeting Minutes</a></li>
  {% endif %}
  <li><a href="/officer/mail/">Webmail Interface</a></li>
  {% if perms.vote.view_poll %}
  <li><a href="{% url 'vote:list' %}">Officer Polls</a></li>
  {% endif %}
  {# TODO(sjdemartini): Add link for officer contact list and member database #}
</ul>

<h2>Administrative Tools</h2>
<ul>
  {% if perms.newsreel.change_news %}
  <li><a href="{% url 'newsreel:list' %}">Newsreel Management</a></li>
  {% endif %}
  {% if perms.exams.change_exam %}
  <li><a href="{% url 'exams:review' %}">Exam Files Management</a></li>
  {% endif %}
  {% if perms.syllabi.change_syllabus %}
  <li><a href="{% url 'syllabi:review' %}">Syllabi Management</a></li>
  {% endif %}
  {% if perms.resumes.change_resume %}
  <li><a href="{% url 'resumes:list' %}">Resume Management</a></li>
  {% endif %}
  <li><a href="/mailman/listinfo/">Public Mailing Lists</a> (<a href="{% url 'mailing-lists:list' %}">Manage All Lists</a>)</li>
  <li><a href="{% url 'courses:instructor-department-list' %}">Instructor Management</a></li>
</ul>

<h2>Candidate Tools</h2>
<ul>
  {# TODO: Add candidate eligibility page once created #}
  {% if perms.candidates.change_candidate %}
  <li><a href="{% url 'candidates:list' %}">Candidate Admin</a></li>
  {% endif %}
  {% if perms.candidates.change_candidaterequirement %}
  <li><a href="{% url 'candidates:edit-requirements' %}">Edit Candidate Requirements</a></li>
  {% endif %}
  {# TODO(sjdemartini): Add links for Candidate houses and house list #}
</ul>

<h2>Contact IT</h2>
{% settings_assign 'IT_ADDRESS' as it_addr %}
<ul>
  <li>Email IT at <a href="mailto:{{ it_addr }}">{{ it_addr }}</a></li>
  <li><a href="/trac/">Introduction</a></li>
  <li><a href="/trac/newticket">Make IT Request or Bug Report</a></li>
  <li><a href="/trac/report/1">View active IT Requests and Bug Reports</a></li>
</ul>
{% endblock content %}

quark/base/templates/base/officers.html
{% extends 'base.html' %}
{% load markup thumbnail %}

{% block content %}
<h1>
  {% block title %}Officers{% endblock title %}
</h1>

{% include '_term_selection.html' %}
{% regroup officers by position as positions %}
{% for position in positions %}
  <div class="officers-section">
    <h3>
      {{ position.grouper }}
      <span>{{ position.grouper.mailing_list }}@tbp</span>
    </h3>
    {% for officer in position.list %}
      <div class="officers-card">
        <div class="officers-img">
          <img src="{{ officer.user.userprofile.picture|thumbnail_url:'officericon' }}"
            alt="{{ officer.user.userprofile.get_common_name }}">
          {% if officer.is_chair %}
            <div class="officers-chair-banner-wrapper">
              <div class="officers-chair-banner">Chair</div>
            </div>
          {% endif %}
        </div>
        <div class="officers-name">
          <span>
          {% if user.is_authenticated %}
            <a href={% url 'user-profiles:detail' officer.user.username %}>{{ officer.user.userprofile.get_common_name }}</a>
          {% else %}
            {{ officer.user.userprofile.get_common_name }}
          {% endif %}
          </span>
          {{ officer.user.get_username }}@tbp
        </div>
        <div class="officers-bio">
          {{ officer.user.userprofile.get_student_org_user_profile.bio }}
        </div>
      </div>
    {% endfor %}
  </div>
{% endfor %}

{% endblock %}

quark/base/templates/base/procrastination.html
{% extends 'base.html' %}

{% block title %}Procrastination{% endblock title %}

{% block intro %}
<h1>Procrastination</h1>
{% endblock intro %}

{% block content %}
{% with is_officer=user.userprofile.is_officer %}
{% with is_member=user.userprofile.is_member %}
{% comment %}
Protect many of these links to allow only the appropriate users.
TODO(sjdemartini): Add permissions for each of these features, rather than
restricting by certain member-type directly in this template.
{% endcomment %}
<ul>
  <li><a href="{% url 'achievements:user' user.id %}">Achievements</a> | <a href="{% url 'achievements:leaderboard' %}">Leaderboard</a></li>

  {# TODO(sjdemartini): Add link to Ad-Hoc Events once ready #}

  {% if is_member %}
  <li><a href="http://widget.mibbit.com/?settings=3faedc31d792eb158e8e8c91f4db4298&amp;server=tbp-irc.berkeley.edu&amp;channel=%23tbpchat&amp;noServerNotices=true&amp;noServerMotd=true&amp;autoConnect=true&amp;nick={{ user.get_username }}">Chat on IRC</a></li>
  <li><a href="{% url 'videos:list' %}">Videos</a></li>
  {% endif %}

  {# TODO(sjdemartini): Add link to IRC quoteboard once ready #}

  {% if is_officer %}
  <li><a href="{% url 'quote-board:list' %}">Quoteboard</a></li>
  {% endif %}
</ul>
{% endwith is_member %}
{% endwith is_officer %}
{% endblock content %}