quark/candidates/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.candidates.views import CandidateCreateView
from quark.candidates.views import CandidateEditView
from quark.candidates.views import CandidateExportView
from quark.candidates.views import CandidateInitiationView
from quark.candidates.views import CandidateListView
from quark.candidates.views import CandidatePhotoView
from quark.candidates.views import CandidatePortalView
from quark.candidates.views import CandidateProgressView
from quark.candidates.views import CandidateProgressByReqView
from quark.candidates.views import CandidateProgressStatsView
from quark.candidates.views import CandidateRequirementsEditView
from quark.candidates.views import ChallengeVerifyView
from quark.candidates.views import ManualCandidateRequirementCreateView
from quark.candidates.views import update_candidate_initiation_status


urlpatterns = patterns(
    '',
    url(r'^$', CandidateListView.as_view(), name='list'),
    url(r'^(?P<candidate_pk>\d+)/$', CandidateEditView.as_view(),
        name='edit'),
    url(r'^(?P<candidate_pk>\d+)/photo$', CandidatePhotoView.as_view(),
        name='photo'),
    url(r'^create/$', CandidateCreateView.as_view(), name='create'),
    url(r'^challenges/$', ChallengeVerifyView.as_view(), name='challenges'),
    url(r'^export/(?P<term_pk>\d+)/$', CandidateExportView.as_view(),
        name='export'),
    url(r'^initiation/$', CandidateInitiationView.as_view(),
        name='initiation'),
    url(r'^initiation/update/$', update_candidate_initiation_status,
        name='initiation-update'),
    url(r'^portal/$', CandidatePortalView.as_view(), name='portal'),
    url(r'^progress/$', CandidateProgressView.as_view(), name='progress'),
    url(r'^progress/by-req/$', CandidateProgressByReqView.as_view(),
        name='progress-by-req'),
    url(r'^progress/stats/$', CandidateProgressStatsView.as_view(),
        name='progress-stats'),
    url(r'^requirements/$',
        CandidateRequirementsEditView.as_view(), name='edit-requirements'),
    url(r'^requirements/add/$',
        ManualCandidateRequirementCreateView.as_view(), name='add-requirement'),
)

quark/exams/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.exams.views import ExamDeleteView
from quark.exams.views import ExamDownloadView
from quark.exams.views import ExamEditView
from quark.exams.views import ExamFlagCreateView
from quark.exams.views import ExamFlagResolveView
from quark.exams.views import ExamReviewListView
from quark.exams.views import ExamUploadView


urlpatterns = patterns(
    '',
    url(r'^review/$', ExamReviewListView.as_view(), name='review'),
    url(r'^upload/$', ExamUploadView.as_view(), name='upload'),
    url(r'^(?P<exam_pk>\d+)/edit/$', ExamEditView.as_view(), name='edit'),
    url(r'^(?P<exam_pk>\d+)/delete/$', ExamDeleteView.as_view(), name='delete'),
    url(r'^(?P<exam_pk>\d+)/download/$', ExamDownloadView.as_view(),
        name='download'),
    url(r'^(?P<exam_pk>\d+)/flag/$', ExamFlagCreateView.as_view(), name='flag'),
    url(r'^(?P<exam_pk>\d+)/flag/(?P<flag_pk>\d+)/$',
        ExamFlagResolveView.as_view(), name='flag-resolve'),
)

quark/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^', include('quark.base.urls',
                      app_name='base')),
    url(r'^accounts/', include('quark.accounts.urls',
                               app_name='accounts',
                               namespace='accounts')),
    url(r'^achievements/', include('quark.achievements.urls',
                                   app_name='achievements',
                                   namespace='achievements')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^alumni/', include('quark.alumni.urls',
                             app_name='alumni',
                             namespace='alumni')),
    url(r'^candidates/', include('quark.candidates.urls',
                                 app_name='candidates',
                                 namespace='candidates')),
    url(r'^courses/', include('quark.courses.urls',
                              app_name='courses',
                              namespace='courses')),
    url(r'^email/', include('quark.emailer.urls',
                            app_name='emailer',
                            namespace='emailer')),
    url(r'^events/', include('quark.events.urls',
                             app_name='events',
                             namespace='events')),
    url(r'^exams/', include('quark.exams.urls',
                            app_name='exams',
                            namespace='exams')),
    url(r'^houses/', include('quark.houses.urls',
                             app_name='houses',
                             namespace='houses')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^industry/', include('quark.companies.urls',
                               app_name='companies',
                               namespace='companies')),
    url(r'^mailing-lists/', include('quark.mailing_lists.urls',
                                    app_name='mailing_lists',
                                    namespace='mailing-lists')),
    url(r'^minutes/', include('quark.minutes.urls',
                              app_name='minutes',
                              namespace='minutes')),
    url(r'^newsreel/', include('quark.newsreel.urls',
                               app_name='newsreel',
                               namespace='newsreel')),
    url(r'^notifications/', include('quark.notifications.urls',
                                    app_name='notifications',
                                    namespace='notifications')),
    url(r'^past-presidents/', include('quark.past_presidents.urls',
                                      app_name='past_presidents',
                                      namespace='past-presidents')),
    url(r'^profile/', include('quark.user_profiles.urls',
                              app_name='user_profiles',
                              namespace='user-profiles')),
    url(r'^project-reports/', include('quark.project_reports.urls',
                                      app_name='project_reports',
                                      namespace='project-reports')),
    url(r'^quote-board/', include('quark.quote_board.urls',
                                  app_name='quote_board',
                                  namespace='quote-board')),
    url(r'^resumes/', include('quark.resumes.urls',
                              app_name='resumes',
                              namespace='resumes')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^videos/', include('quark.videos.urls',
                             app_name='videos',
                             namespace='videos')),
    url(r'^vote/', include('quark.vote.urls',
                           app_name='vote',
                           namespace='vote')),
)

# Add flatpages URLs
urlpatterns += patterns(
    'django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^about/contact/$', 'flatpage', {'url': '/about/contact/'},
        name='contact'),
    url(r'^about/eligibility/$', 'flatpage', {'url': '/about/eligibility/'},
        name='eligibility'),
    url(r'^people/committees/$', 'flatpage', {'url': '/people/committees/'},
        name='committees'),
    url(r'^student-resources/$', 'flatpage', {'url': '/student-resources/'},
        name='student-resources'),
    url(r'^resume-critique/$', 'flatpage', {'url': '/resume-critique/'},
        name='resume-critique'),
    url(r'^mock-interviews/$', 'flatpage', {'url': '/mock-interviews/'},
        name='mock-interviews'),
    url(r'^partnership_program/$', 'flatpage', {'url': '/partnership_program/'},
        name='partnership_program'),
)

# Handle page redirects
urlpatterns += patterns(
    '',
    url(r'^indrel/$', RedirectView.as_view(pattern_name='industry')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quark/candidates/templates/candidates/_challenge_table.html
{% comment %}
This template is included in edit.html and portal.html to show a table with
all the challenges a candidate has submitted.

Any template that includes this must include footable.html to activate the
footable.
{% endcomment %}
{% load template_utils %}

<table class="footable bordered stylized">
  <thead>
    <tr>
      <th>Challenge Description</th>
      <th data-hide="phone">Officer</th>
      <th>Type</th>
      <th>Status</th>
      <th data-hide="phone,tablet">Reason</th>
    </tr>
  </thead>
  <tbody>
    {% for challenge in challenges|get_item:challenge_type %}
    <tr>
      <td>{{ challenge.description }}</td>
      <td>{{ challenge.verifying_user.userprofile.get_common_name }}</td>
      <td>{{ challenge.challenge_type }}</td>
      <td>{{ challenge.get_verified_display }}</td>
      <td>{{ challenge.reason|default:'&mdash;' }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

quark/candidates/templates/candidates/_form_field.html
<div class="form-entry{% if field.errors %} form-entry-error{% endif %}{% if field.field.required %} form-entry-required{% endif %}">
  {{ field.label_tag }}
  <div class="form-input">
    {{ field }}
    {% if field.help_text %}<span class="help-text">{{ field.help_text }}</span>{% endif %}
    {% if field.errors %}<div class="form-errors">{{ field.errors }}</div>{% endif %}
  </div>
</div>

quark/candidates/templates/candidates/_req_progress.html
<table class="footable bordered stylized">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th data-type="numeric" data-sort-initial="descending">Unfinished</th>
      {% if req_info.is_event_req %}
      <th data-type="numeric">Signed up for</th>
      {% endif %}
    </tr>
  </thead>

  <tbody>
    {% for candidate, req, num_unfinished in progresses %}
    {% if req.completed < req.required %}
      <tr>
        <td><a href="{% url 'candidates:edit' candidate.pk %}">{{ candidate.user.first_name }}</a></td>
        <td><a href="{% url 'candidates:edit' candidate.pk %}">{{ candidate.user.last_name }}</a></td>
        <td data-value="{{ num_unfinished }}">
          {% if req_info.is_event_req %}
            <li class="candidate-progress-entry">{{ num_unfinished }}
              {% if req.warning %}
                {% if req.remaining > 0 %}
                  <div class="candidate-progress-warning">Warning: Only {{ req.remaining }} event{{ req.remaining|pluralize }} remaining.</div>
                {% else %}
                  <div class="candidate-progress-warning">Warning: No events remaining.</div>
                {% endif %}
              {% endif %}
            </li>
          {% else %}
            <li class="candidate-progress-entry">{{ num_unfinished }}</li>
          {% endif %}
        </td>
        {% if req_info.is_event_req %}
        <td data-value="{{ req.signed_up }}">{{ req.signed_up }}</td>
        {% endif %}
      </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>

quark/candidates/templates/candidates/challenge_verification_email.html
{% load template_utils %}

Hi {{ challenge.verifying_user.first_name }},

{{ candidate }} is asking for a verification of the following {{ challenge.challenge_type }} challenge from you:

{{ challenge.description }}

To verify this challenge, please visit the following URL: {% full_url 'candidates:challenges' %}

quark/candidates/templates/candidates/delete_requirement.html
{% extends 'base.html' %}

{% block title %}Delete Candidate Requirement{% endblock title %}

{% block intro %}
<h1>Delete {{ requirement.get_name }} {{ requirement.get_requirement_type_display}} Requirement</h1>
{% endblock %}

{% block content %}
<p>Are you SURE you want to delete this requirement? THIS ACTION IS NOT REVERSIBLE.</p>

<form method="post">
  {% csrf_token %}
  {% include '_form.html' %}
  <div>
    <input type="submit" value="Delete">
  </div>
</form>

<div>
  <a href="{% url 'candidates:edit-requirements' %}"><strong>Edit requirements instead</strong></a>
</div>
{% endblock content %}

quark/candidates/templates/candidates/edit_requirements.html
{% extends 'base.html' %}

{% block title %}Edit Candidate Requirements{% endblock title %}

{% block intro %}
<h1>Edit Candidate Requirements for {{ term.verbose_name }}</h1>
{% endblock intro %}

{% block content %}
{# TODO(ericdwang): add the rest of editing requirements #}
NOTE: Only requirements that require more than zero credits will be displayed in candidate admin/portal!

<form method="post" class="form-narrow">
  {% csrf_token %}
  {{ form.management_form }}

  {% include 'candidates/_individual_requirement.html' with display_req_type='Event' entries=req_types.event %}
  {% include 'candidates/_individual_requirement.html' with display_req_type='Challenge' entries=req_types.challenge %}
  {% include 'candidates/_individual_requirement.html' with display_req_type='Exam File' entries=req_types.exam %}
  {% include 'candidates/_individual_requirement.html' with display_req_type='Syllabus' entries=req_types.syllabus %}
  {% include 'candidates/_individual_requirement.html' with display_req_type='Resume' entries=req_types.resume %}
  {% include 'candidates/_individual_requirement.html' with display_req_type='Manual' entries=req_types.manual %}
  <a href="{% url 'candidates:add-requirement' %}">Add manual requirement</a>

  <p>
    <input type="submit" value="Update">
  </p>
</form>

<p>
  <a href="{% url 'candidates:list' %}?term={{ candidate.term.get_url_name }}"><strong>Back to {{ term.verbose_name }} Candidates</strong></a>
</p>
{% endblock content %}

quark/candidates/templates/candidates/initiation.html
{% extends 'base.html' %}

{% load static %}

{% block intro %}
<h1>
  {% block title %}Initiation for {{ display_term_name }} Candidates{% endblock title %}
</h1>
{% endblock intro %}

{% block content %}
{% include '_term_selection.html' %}

{% if candidates %}
<p>
  <div>Total number of candidates: {{ candidates|length }}</div>
  <div>Number of candidates initiated: <span id="num-initiated">0</span></div>
</p>

<p>Check off the candidates who have initiated.</p>

<table class="footable stylized">
  <thead>
    <tr>
      <th data-sort-initial="true">First Name</th>
      <th>Last Name</th>
      <th data-hide="phone" data-sort-ignore="true">Picture</th>
      <th data-hide="phone">Requirements Completed</th>
      <th data-sort-ignore="true">Initiated?</th>
    </tr>
  </thead>
  <tbody>
  {% for candidate in candidates %}
  <tr class="{% if candidate.initiated %}candidate-initiated{% else %}candidate-not-initiated{% endif %}" data-candidate-pk="{{ candidate.pk }}">
    {% with cand_user_profile=candidate.user.userprofile %}
    <td ><a href="{% url 'candidates:edit' candidate.pk %}">{{ cand_user_profile.get_verbose_first_name }}</a></td>
    <td><a href="{% url 'candidates:edit' candidate.pk %}">{{ candidate.user.last_name }}</a></td>
    <td>
      {% if candidate.photo %}
      <a href="{{ candidate.photo.url }}"><img src="{{ candidate.photo.url }}" alt="{{ candidate.user.get_full_name }}" class="candidate-thumbnail"></a>
      {% else %}
      <img src="{% static 'images/missing.jpg' %}" alt="No photo for {{ candidate.user.get_full_name }}" class="candidate-thumbnail">
      {% endif %}
    </td>
    {% with progress=candidate.get_progress %}
    <td data-value="{{ progress.completed }}">
      {{ progress.completed }} / {{ progress.required }}
    </td>
    <td>
      <input type="checkbox" class="initiated-checkbox"
        name="{{ candidate.pk }}" onclick="initiateCandidate(event)"
        {% if candidate.initiated %}checked{% endif %}>
      <i class="fa fa-spinner fa-spin loading" style="display: none"></i>
    </td>
    {% endwith progress %}

    {% endwith cand_user_profile %}
  </tr>
  {% endfor %}
</table>

{% else %}
<p>There are no candidates for {{ display_term }}.</p>
{% endif %}

{% endblock content %}

{% block extra_js %}
{% include '_footable.html' with include_sort=True %}
<script>
  function updateNumInitiated() {
    var initiatedNode = $('#num-initiated');
    var checkboxesChecked = $('.initiated-checkbox:checked');
    initiatedNode.text(checkboxesChecked.size());
  }

  updateNumInitiated();

  function initiateCandidate(event) {
    var candidateRow = $(event.target).parents('tr');
    var alreadyInitiated = candidateRow.hasClass('candidate-initiated');
    var checkbox = $(event.target);
    var req = $.post('{% url 'candidates:initiation-update' %}', {
      candidate: candidateRow.data('candidate-pk'),
      initiated: !alreadyInitiated  // Change their initiation status
    });
    // Show the spinner icon:
    var spinner = checkbox.next();
    spinner.show();
    req.done(function() {
      // Change the display to indicate that this candidate's initation status
      // has changed
      updateNumInitiated();
      candidateRow.toggleClass('candidate-initiated');
      candidateRow.toggleClass('candidate-not-initiated');
    });
    req.fail(function() {
      // Uncheck the checkbox
      checkbox.prop('checked', !checkbox.prop('checked'));
      // TODO(sjdemartini): Somehow provide some feedback to the user about what
      // went wrong?
    });
    req.always(function() {
      // Hide the spinner icon
      spinner.fadeOut(200);
    });
  }
</script>
{% endblock extra_js %}

quark/candidates/templates/candidates/photo.html
{% extends 'base.html' %}

{% block title %}Upload Candidate Photo{% endblock title %}

{% block intro %}
<h1>Upload Candidate Photo for {{ candidate.user.userprofile.get_common_name }}</h1>
{% endblock intro %}

{% block content %}
<div>
  <p>Current photo:</p>
  {% if candidate.photo %}
  <img src="{{ candidate.photo.url }}" alt="{{ candidate.user.userprofile.get_common_name }}" class="candidate-photo">
  {% else %}
  No photo uploaded yet.
  {% endif %}
</div>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.photo }}
  <div>
    <input type="submit" value="Upload">
  </div>
</form>

<div>
  <a href=" {% url 'candidates:edit' candidate.pk %}"><strong>Candidate Management for {{ candidate.user.userprofile.get_common_name }}</strong></a>
</div>
{% endblock content %}

quark/candidates/templates/candidates/portal.html
{% extends 'base.html' %}
{% load template_utils %}

{% block title %}Candidate Portal{% endblock title %}

{% block intro %}
<h1>Candidate Portal</h1>
{% endblock intro %}

{% block content %}
<h2>Event Requirements</h2>
{% for entry in req_types.event %}
{% if entry.requirement.get_name != 'Elective' %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}
<ul>
  {% with event_type=entry.requirement.eventcandidaterequirement.event_type.name %}
  {% if attended_events|get_item:event_type|length == 0 and past_signup_events|get_item:event_type|length == 0 and future_signup_events|get_item:event_type|length == 0 %}
  No signups or attendance for {{ event_type }} events.
  {% else %}
  {% for event in past_signup_events|get_item:event_type %}
  <li><del><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></del></li>
  {% endfor %}
  {% for event in attended_events|get_item:event_type %}
  <li><strong><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></strong></li>
  {% endfor %}
  {% for event in future_signup_events|get_item:event_type %}
  <li><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></li>
  {% endfor %}
  {% endif %}
  {% endwith %}
</ul>
{% else %}
  {% if entry.credits_needed > 0 %}
  <h3>Elective</h3>
  <div><strong>[{{ attended_elective_events|length }} / {{ entry.credits_needed }}]</strong></div>
  <ul>
    {% if attended_elective_events|length == 0 and future_signup_elective_events|length == 0 %}
    No signups or attendance for Elective events. If you attend more than the required number of events in any event category, those additional events will count as Elective events.
    {% else %}
    {% for event in attended_elective_events %}
    <li><strong><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></strong> ({{ event.event_type.name }})</li>
    {% endfor %}
    {% for event in future_signup_elective_events %}
    <li><a href="{{ event.get_absolute_url }}">{{ event.name }}</a> ({{ event.event_type.name }})</li>
    {% endfor %}
    {% endif %}
  </ul>
  {% endif %}
{% endif %}
{% empty %}
There are no Event requirements.
{% endfor %}

<h2>Challenge Requirements</h2>
{% for entry in req_types.challenge %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}
{% with challenge_type=entry.requirement.challengecandidaterequirement.challenge_type.name %}
{% if challenges|get_item:challenge_type %}
{% include 'candidates/_challenge_table.html' %}
{% else %}
No {{ challenge_type }} challenges submitted.
{% endif %}
{% endwith challenge_type %}
{% empty %}
There are no Challenge requirements.
{% endfor %}

<h3>Request Challenges</h3>
<form method="post">
  {% csrf_token %}
  {% include '_form.html' %}
  <div>
    <input type="submit" value="Submit">
  </div>
</form>

<h2>Exam File Requirements</h2>
{% for entry in req_types.exam %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}

<h3>Approved Exams Uploaded</h3>
<ul>
  {% for exam in approved_exams %}
  <li><em>{{ exam }}</em></li>
  {% empty %}
  No approved exams uploaded.
  {% endfor %}
</ul>

<h3>Uploaded Exams Awaiting Verification</h3>
<ul>
  {% for exam in unverified_exams %}
  <li><em>{{ exam }}</em></li>
  {% empty %}
  No uploaded exams awaiting verification.
  {% endfor %}
</ul>
<p>Note: all exams need to be verified by officers to check that they are valid.</p>

<h3>Blacklisted Exams Uploaded</h3>
<ul>
  {% for exam in blacklisted_exams %}
  <li><em>{{ exam }}</em></li>
  {% empty %}
  No blacklisted exams uploaded.
  {% endfor %}
</ul>
<p>Note: uploaded exams from blacklisted professors DO NOT count towards candidate requirements.</p>

{% empty %}
No exams uploaded.
{% endfor %}
<p>You can upload exams <a href="{% url 'exams:upload' %}"><strong>here</strong></a>.</p>

<h2>Syllabi Requirements</h2>
{% for entry in req_types.syllabus %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}

<h3>Approved Syllabi Uploaded</h3>
<ul>
  {% for syllabus in approved_syllabi %}
  <li><em>{{ syllabus }}</em></li>
  {% empty %}
  No approved syllabi uploaded.
  {% endfor %}
</ul>

<h3>Uploaded Syllabi Awaiting Verification</h3>
<ul>
  {% for syllabus in unverified_syllabi %}
  <li><em>{{ syllabus }}</em></li>
  {% empty %}
  No uploaded exams awaiting verification.
  {% endfor %}
</ul>
<p>Note: all exams need to be verified by officers to check that they are valid.</p>

<h3>Blacklisted Syllabi Uploaded</h3>
<ul>
  {% for syllabus in blacklisted_syllabi %}
  <li><em>{{ syllabus }}</em></li>
  {% empty %}
  No blacklisted syllabi uploaded.
  {% endfor %}
</ul>
<p>Note: uploaded exams from blacklisted professors DO NOT count towards candidate requirements.</p>
{% empty %}
No syllabi uploaded.

{% endfor %}
<p>You can upload syllabi <a href="{% url 'syllabi:upload' %}"><strong>here</strong></a>.</p>

<h2>Resume Requirements</h2>
{% for entry in req_types.resume %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}
<p><strong>Resume status</strong>: {{ resume_status }}</p>
{% empty %}
There are no Resume requirements.
{% endfor %}
<p>You can upload your resume <a href="{% url 'resumes:edit' %}"><strong>here</strong></a>.</p>

<h2>Manual Requirements</h2>
{% for entry in req_types.manual %}
{% include 'candidates/_individual_portal_progress.html' with entry=entry %}
{% empty %}
There are no Manual requirements.
{% endfor %}

{% endblock content %}

{% block extra_js %}
{% include '_footable.html' %}
{% endblock extra_js %}

quark/candidates/templates/candidates/progress.html
{% extends 'candidates/progress_base.html' %}

{% block selectors %}
{% include 'candidates/_house_selection.html' %}
{% endblock selectors %}

{% block content %}

<p>Below is a list of all candidates who have not attended and are not signed up for enough events to complete their requirements.</p>

<p>A red warning indicates that there aren't enough events remaining for this candidate to complete that requirement.</p>

<table class="footable bordered stylized">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Requirements</th>
    </tr>
  </thead>
  <tbody>
    {% for candidate, progress_dict in progress.items %}
      {% if not progress_dict.all_requirements_complete %}
      <tr>
        <td><a href="{% url 'candidates:edit' candidate.pk %}">{{ candidate.user.first_name }}</a></td>
        <td><a href="{% url 'candidates:edit' candidate.pk %}">{{ candidate.user.last_name }}</a></td>
        <td>
          <ul>
          {% for req in progress_dict.requirements %}
            {% if req.completed < req.required %}
              {% if req.requirement.requirement_type == req.requirement.EVENT %}
                <li class="candidate-progress-entry"><span class="candidate-progress-requirement">{{ req.requirement.get_name }}:</span> {{ req.completed }}/{{ req.required }} completed (signed up for {{ req.signed_up }})
                  {% if req.warning %}
                    {% if req.remaining > 0 %}
                      <div class="candidate-progress-warning">Warning: Only {{ req.remaining }} event{{ req.remaining|pluralize }} remaining.</div>
                    {% else %}
                      <div class="candidate-progress-warning">Warning: No events remaining.</div>
                    {% endif %}
                  {% endif %}
                </li>
              {% else %}
                <li class="candidate-progress-entry"><span class="candidate-progress-requirement">{{ req.requirement.get_name }}:</span> {{ req.completed }}/{{ req.required }}</li>
              {% endif %}
            {% endif %}
          {% endfor %}
          </ul>
        </td>
      </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

{% block extra_js %}
{% include '_footable.html' with include_sort=True %}
{% endblock extra_js %}

quark/candidates/templates/candidates/progress_base.html
{% extends 'base.html' %}

{% block intro %}

<h1>
{% block title %}
Candidate Progress Tracking
{% endblock title %}
</h1>

{% url 'candidates:progress' as progress_url %}
{% url 'candidates:progress-stats' as progress_stats_url %}
{% url 'candidates:progress-by-req' as progress_by_req_url %}
<div class="btn-group">
  {% if request.path == progress_url %}
  <div class="btn btn-sm selected">By Candidate</div>
  {% else %}
  <a href="{{ progress_url }}?term={{ display_term.get_url_name }}" class="btn btn-sm">By Candidate</a>
  {% endif %}

  {% if request.path == progress_by_req_url %}
  <div class="btn btn-sm selected">By Requirement</div>
  {% else %}
  <a href="{{ progress_by_req_url }}?term={{ display_term.get_url_name }}" class="btn btn-sm">By Requirement</a>
  {% endif %}

  {% if request.path == progress_stats_url %}
  <div class="btn btn-sm selected">Statistics</div>
  {% else %}
  <a href="{{ progress_stats_url }}?term={{ display_term.get_url_name }}" class="btn btn-sm">Statistics</a>
  {% endif %}
</div>

{% include '_term_selection.html' %}

{% block selectors %}
{% endblock selectors %}

<p>
  <a href="{% url 'candidates:list' %}?term={{ display_term.get_url_name }}"><strong>Back to {{ display_term.verbose_name }} Candidates</strong></a>
</p>
{% endblock intro %}