quark/events/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.emailer.views import EventEmailerView
from quark.events.views import AllTimeLeaderboardListView
from quark.events.views import attendance_delete
from quark.events.views import attendance_search
from quark.events.views import attendance_submit
from quark.events.views import AttendanceRecordView
from quark.events.views import EventBuilderView
from quark.events.views import EventCancelView
from quark.events.views import EventCreateView
from quark.events.views import EventDetailView
from quark.events.views import EventListView
from quark.events.views import EventSignUpView
from quark.events.views import event_revive
from quark.events.views import event_unsignup
from quark.events.views import EventUpdateView
from quark.events.views import ical
from quark.events.views import IndividualAttendanceListView
from quark.events.views import LeaderboardListView

urlpatterns = patterns(
    '',
    url(r'^$', EventListView.as_view(), name='list'),
    url(r'^builder/$', EventBuilderView.as_view(), name='builder'),
    url(r'^add/$', EventCreateView.as_view(), name='add'),
    url(r'^(?P<event_pk>\d+)/$', EventDetailView.as_view(),
        name='detail'),
    url(r'^(?P<event_pk>\d+)/edit/$', EventUpdateView.as_view(), name='edit'),
    url(r'^(?P<event_pk>\d+)/cancel/$', EventCancelView.as_view(),
        name='cancel'),
    url(r'^(?P<event_pk>\d+)/revive/$', event_revive,
        name='revive'),
    url(r'^(?P<event_pk>\d+)/signup/$', EventSignUpView.as_view(),
        name='signup'),
    url(r'^(?P<event_pk>\d+)/unsignup/$', event_unsignup,
        name='unsignup'),
    url(r'^(?P<event_pk>\d+)/attendance/$', AttendanceRecordView.as_view(),
        name='attendance'),
    url(r'^(?P<event_pk>\d+)/email/$', EventEmailerView.as_view(),
        name='email'),
    url(r'^attendance/delete/$', attendance_delete, name='attendance-delete'),
    url(r'^attendance/search/$', attendance_search, name='attendance-search'),
    url(r'^attendance/submit/$', attendance_submit, name='attendance-submit'),
    url(r'^user/(?P<username>[a-zA-Z0-9._-]+)/$',
        IndividualAttendanceListView.as_view(), name='individual-attendance'),
    url(r'^calendar/$', EventListView.as_view(show_all=True,
        template_name='events/calendar.html'), name='calendar'),
    url(r'^leaderboard/$', LeaderboardListView.as_view(), name='leaderboard'),
    url(r'^leaderboard/all-time/$',
        AllTimeLeaderboardListView.as_view(), name='all-time-leaderboard'),
    url(r'^events.ics$', ical, name='ical'),
    url(r'^(?P<event_pk>\d+)/event.ics$', ical, name='event-ical'),
)

quark/houses/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.houses.views import assign_house
from quark.houses.views import HouseMembersEditView
from quark.houses.views import HouseMembersListView
from quark.houses.views import unassign_house


urlpatterns = patterns(
    '',
    url(r'^$', HouseMembersListView.as_view(), name='list'),
    url(r'^assign/$', assign_house, name='assign'),
    url(r'^edit/$', HouseMembersEditView.as_view(), name='edit'),
    url(r'^unassign/$', unassign_house, name='unassign'),
)

quark/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^', include('quark.base.urls',
                      app_name='base')),
    url(r'^accounts/', include('quark.accounts.urls',
                               app_name='accounts',
                               namespace='accounts')),
    url(r'^achievements/', include('quark.achievements.urls',
                                   app_name='achievements',
                                   namespace='achievements')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^alumni/', include('quark.alumni.urls',
                             app_name='alumni',
                             namespace='alumni')),
    url(r'^candidates/', include('quark.candidates.urls',
                                 app_name='candidates',
                                 namespace='candidates')),
    url(r'^courses/', include('quark.courses.urls',
                              app_name='courses',
                              namespace='courses')),
    url(r'^email/', include('quark.emailer.urls',
                            app_name='emailer',
                            namespace='emailer')),
    url(r'^events/', include('quark.events.urls',
                             app_name='events',
                             namespace='events')),
    url(r'^exams/', include('quark.exams.urls',
                            app_name='exams',
                            namespace='exams')),
    url(r'^houses/', include('quark.houses.urls',
                             app_name='houses',
                             namespace='houses')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^industry/', include('quark.companies.urls',
                               app_name='companies',
                               namespace='companies')),
    url(r'^mailing-lists/', include('quark.mailing_lists.urls',
                                    app_name='mailing_lists',
                                    namespace='mailing-lists')),
    url(r'^minutes/', include('quark.minutes.urls',
                              app_name='minutes',
                              namespace='minutes')),
    url(r'^newsreel/', include('quark.newsreel.urls',
                               app_name='newsreel',
                               namespace='newsreel')),
    url(r'^notifications/', include('quark.notifications.urls',
                                    app_name='notifications',
                                    namespace='notifications')),
    url(r'^past-presidents/', include('quark.past_presidents.urls',
                                      app_name='past_presidents',
                                      namespace='past-presidents')),
    url(r'^profile/', include('quark.user_profiles.urls',
                              app_name='user_profiles',
                              namespace='user-profiles')),
    url(r'^project-reports/', include('quark.project_reports.urls',
                                      app_name='project_reports',
                                      namespace='project-reports')),
    url(r'^quote-board/', include('quark.quote_board.urls',
                                  app_name='quote_board',
                                  namespace='quote-board')),
    url(r'^resumes/', include('quark.resumes.urls',
                              app_name='resumes',
                              namespace='resumes')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^videos/', include('quark.videos.urls',
                             app_name='videos',
                             namespace='videos')),
    url(r'^vote/', include('quark.vote.urls',
                           app_name='vote',
                           namespace='vote')),
)

# Add flatpages URLs
urlpatterns += patterns(
    'django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^about/contact/$', 'flatpage', {'url': '/about/contact/'},
        name='contact'),
    url(r'^about/eligibility/$', 'flatpage', {'url': '/about/eligibility/'},
        name='eligibility'),
    url(r'^people/committees/$', 'flatpage', {'url': '/people/committees/'},
        name='committees'),
    url(r'^student-resources/$', 'flatpage', {'url': '/student-resources/'},
        name='student-resources'),
    url(r'^resume-critique/$', 'flatpage', {'url': '/resume-critique/'},
        name='resume-critique'),
    url(r'^mock-interviews/$', 'flatpage', {'url': '/mock-interviews/'},
        name='mock-interviews'),
    url(r'^partnership_program/$', 'flatpage', {'url': '/partnership_program/'},
        name='partnership_program'),
)

# Handle page redirects
urlpatterns += patterns(
    '',
    url(r'^indrel/$', RedirectView.as_view(pattern_name='industry')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quark/houses/models.py
from django.conf import settings
from django.db import models

from quark.base.models import Term


class House(models.Model):
    """A house that contains a subsection of an organization's members.

    HouseMember objects reference Houses to link members to the houses they
    have been a part of.
    """
    name = models.CharField(max_length=16, unique=True)
    mailing_list = models.CharField(
        max_length=16, blank=True,
        help_text='The mailing list name, not including the @domain.')

    def __unicode__(self):
        return self.name


class HouseMember(models.Model):
    """A member of a house."""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='housemember')
    term = models.ForeignKey(Term)
    house = models.ForeignKey(House)

    is_leader = models.NullBooleanField(
        default=None,
        help_text='Is this person the house leader?')

    class Meta(object):
        unique_together = (('user', 'term'), ('term', 'house', 'is_leader'))
        permissions = (
            ('view_housemember', 'Can view all houses and members'),
        )

    def __unicode__(self):
        return '%s - %s (%s %d)' % (
            self.user.userprofile.get_common_name(), self.house.name,
            self.term.get_term_display(), self.term.year)

quark/houses/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db.models import Max, Q
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import ListView

from quark.base.models import Officer
from quark.base.models import OfficerPosition
from quark.base.models import Term
from quark.base.views import TermParameterMixin
from quark.houses.models import House
from quark.houses.models import HouseMember
from quark.shortcuts import get_object_or_none
from quark.utils.ajax import json_response


class HouseMembersEditView(TermParameterMixin, ListView):
    context_object_name = 'eligible_house_members'
    current_term = Term.objects.get_current_term()
    model = get_user_model()
    template_name = 'houses/edit.html'

    @method_decorator(login_required)
    @method_decorator(permission_required('houses.add_housemember',
                      raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(HouseMembersEditView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        # Select all users who are either officers or candidates this term
        return get_user_model().objects.filter(
            Q(officer__term=self.display_term) |
            Q(candidate__term=self.display_term)).select_related(
            'userprofile').order_by('userprofile').distinct()

    def get_context_data(self, **kwargs):
        context = super(HouseMembersEditView, self).get_context_data(
            **kwargs)

        context['houses'] = House.objects.all()

        # Find house leaders and candidates to check groups without querying DB
        house_leader = get_object_or_none(OfficerPosition,
                                          short_name='house-leaders')

        context['house_leaders'] = get_user_model().objects.filter(
            officer__term=self.display_term,
            officer__position=house_leader)

        context['candidates'] = get_user_model().objects.filter(
            candidate__term=self.display_term)

        # Create a dict with user ids as keys mapping to house names to identify
        # users who are already members of a house.
        house_members = HouseMember.objects.filter(
            user__in=context['eligible_house_members'],
            term=self.display_term).select_related('house', 'user')
        user_house_dict = {}

        for member in house_members:
            user_house_dict[member.user.id] = member.house.mailing_list

        context['user_houses'] = user_house_dict

        return context


class HouseMembersListView(TermParameterMixin, ListView):
    context_object_name = 'house_members'
    model = HouseMember
    template_name = 'houses/list.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HouseMembersListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        # Display house leader first, then candidates, then others
        return HouseMember.objects.filter(term=self.display_term).annotate(
            has_initiated=Max('user__candidate__initiated')).order_by(
            'house__name', '-is_leader', 'has_initiated').select_related(
            'user__userprofile', 'user__studentorguserprofile', 'house')

    def get_context_data(self, **kwargs):
        context = super(HouseMembersListView, self).get_context_data(**kwargs)

        # Find candidates in this term to check groups without querying the DB
        context['candidates'] = get_user_model().objects.filter(
            candidate__term=self.display_term)

        return context


@require_POST
@permission_required('houses.add_housemember', raise_exception=True)
def assign_house(request):
    """Assign an officer or candidate to a house for the current semester.

    The user is specified by a userPK post parameter, the house is specified by
    a houseName post parameter, and the term is specified by a term post
    parameter which is the url name of the display term.
    """
    user_pk = request.POST.get('userPK')
    user = get_user_model().objects.get(pk=user_pk)
    house_name = request.POST.get('houseName')
    house = House.objects.get(mailing_list=house_name)
    term = Term.objects.get_by_url_name(request.POST.get('term'))

    house_member, created = HouseMember.objects.get_or_create(
        user=user, term=term, defaults={'house': house})

    # Find out if the user is a house leader for setting is_leader correctly
    user_house_leader = get_object_or_none(
        Officer, position__short_name='house-leaders',
        user__id=user_pk, term=term)

    if user_house_leader is not None:
        # Find out if there is already a house leader for this house
        existing_house_leader = get_object_or_none(
            HouseMember, house=house, is_leader=True, term=term)

        if existing_house_leader is not None:
            # If there is already a house leader in that house and we're trying
            # to add a house leader, delete any newly created HouseMember object
            # and return a 400 error to be handled by jQuery
            if created:
                house_member.delete()

            return json_response(status=400)
        else:
            house_member.is_leader = True

    # If an object was gotten, the user was in a different house previously
    if not created:
        house_member.house = house

    house_member.save()

    return json_response()


@require_POST
@permission_required('houses.delete_housemember', raise_exception=True)
def unassign_house(request):
    """Remove an officer or candidate from his or her house this semester.

    The user is specified by a userPK post parameter, and the house doesn't
    matter as a user can only be in one house in a given semester. The term
    is specified by a term post parameter which is the url name of the display
    term.
    """
    user_pk = request.POST.get('userPK')
    term = Term.objects.get_by_url_name(request.POST.get('term'))
    # Delete the HouseMember object for this user/term if it exists
    try:
        HouseMember.objects.get(user__pk=user_pk, term=term).delete()
    except HouseMember.DoesNotExist:
        # Fine if the HouseMember does not exist since we wanted to remove it
        pass
    return json_response()

quark/houses/templates/houses/edit.html
{% extends 'base.html' %}

{% load template_utils %}

{% block intro %}
<h1>
  {% block title %}Houses for {{ display_term }}{% endblock title %}
</h1>

{% url 'houses:edit' as houses_edit %}
{% include '_term_selection.html' with float_right=False url_base=houses_edit %}
{% endblock intro %}


{% block content %}
<p>
  <a href="{% url 'houses:list' %}?term={{ display_term_url_name }}" class="btn">
    <i class="fa fa-check-circle"></i> Done Editing
  </a>
</p>

<p>Drag and drop the users below to assign or unassign them to houses. Changes will be saved automatically, and users will appear sorted on the main houses page independently of their order here.</p>

{% for house in houses %}
<div class="house-section">
  <h3>{{ house.name }}</h3>
    <ul id="{{ house.mailing_list }}-members-list" class="sortable-list ui-sortable {{ house.mailing_list }} members-list">
    </ul>
  </h3>
</div>
{% endfor %}

{% if eligible_house_members %}
<h3>Unassigned Users</h3>
<div class="unassigned-section">
  <ul id="unassigned-list" class="sortable-list ui-sortable">
    {% for entry in eligible_house_members %}
    <li id="user-{{ entry.pk }}" class="sortable-item house-member {{ user_houses|get_item:entry.id }}">
      <div class="avatar">
        {% include '_user_thumbnail.html' with user_profile=entry.userprofile %}
      </div>
      <div class="user-name
        {% if entry in house_leaders %} house-leader
        {% elif entry in candidates %} candidate
        {% endif %}">{{ entry.userprofile.get_common_name }}
      </div>
    </li>
    {% endfor %}
  </div>
</ul>
{% endif %}

{% endblock content %}

{% block extra_js %}
<script>
$(document).ready(function() {
  $('ul.sortable-list').sortable({
    connectWith: 'ul.sortable-list',
    update: function(event, ui) {
      var self = ui.item;
      // Get user id and house name from element ids
      var userID = self.attr('id').slice(5);
      var houseName = self.parent().attr('id').split('-')[0];

      var success;

      // If the element has been dragged into a house container, add the
      // user to the corresponding house. Otherwise they have been dragged
      // out of a house, so remove them from their previous house.
      if (houseName != 'unassigned') {
        $.post('{% url 'houses:assign' %}', {
          userPK: userID,
          houseName: houseName,
          term: '{{ display_term_url_name }}'
        }).done(function() {
          self.attr('class', 'sortable-item house-member ' + houseName);
        }).fail(function() {
          // If the post fails, put the user back in their previous house
          var prevHouseName = self.attr('class').slice(27);
          var prevHouseList;
          if ((prevHouseName == 'None') || (prevHouseName == 'unassigned')) {
            prevHouseList = $('#unassigned-list');
          } else {
            prevHouseList = $('#' + prevHouseName + '-members-list');
          }
          if (prevHouseList) {
            self.detach();
            prevHouseList.prepend(self);
          }
        });
      } else {
        $.post('{% url 'houses:unassign' %}', {
          userPK: userID,
          term: '{{ display_term_url_name }}'
        }).done(function() {
          self.attr('class', 'sortable-item house-member ' + houseName);
        });
      }
   }
  });

  // On page load, move all users who are already in houses from the unassigned
  // list to their house's list
  $('li.sortable-item').each(function() {
    var self = $(this);
    var houseName = self.attr('class').slice(27);
    var houseList = $('#' + houseName + '-members-list');
    if (houseList && houseName != 'None') {
      self.detach();
      houseList.append(self);
    }
  });

  // Reorder the lists: house leaders first, then candidates, then officers
  $('.candidate').parent().each(function() {
    $(this).parent().prepend(this);
  });

  $('.house-leader').parent().each(function() {
    $(this).parent().prepend(this);
  });
});

</script>
{% endblock extra_js %}

quark/houses/templates/houses/list.html
{% extends 'base.html' %}

{% block intro %}

<h1>
  {% block title %}Houses for {{ display_term }}{% endblock title %}
</h1>

{% url 'houses:list' as list_houses %}
{% include '_term_selection.html' with float_right=False url_base=list_houses %}
{% endblock intro %}

{% block content %}

<p>Below are the <strong>house leaders</strong>, <i>candidates</i>, and officers that make up each house in {{ display_term_name}}.</p>

{% regroup house_members by house as houses %}
{% for house in houses %}
<div class="house-section">
  <h3>{{ house.grouper }}</h3>
  <ul id="{{ house.grouper.mailing_list }}-members-list" class="{{ house.grouper.mailing_list }} members-list">
    {% for house_member in house.list %}
    <li id="user_{{ house_member.user.pk}}" class="house-member {{house.grouper.mailing_list }}">
      <div class="avatar">
        {% include '_user_thumbnail.html' with user_profile=house_member.user.userprofile %}
      </div>
      <div class="user-name
        {% if house_member.is_leader %} house-leader
        {% elif house_member.user in candidates %} candidate
        {% endif %}">
        <a href="{% url 'user-profiles:detail' house_member.user.username %}">{{ house_member.user.userprofile.get_common_name }}</a>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endfor %}

{% if perms.houses.add_housemember %}
<p>
  <a href="{% url 'houses:edit' %}?term={{ display_term_url_name }}" class="btn">
    <i class="fa fa-edit"></i> Edit Houses
  </a>
</p>
{% endif %}

{% endblock content %}