quark/quote_board/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from quark.quote_board.views import QuoteCreateView
from quark.quote_board.views import QuoteDetailView
from quark.quote_board.views import QuoteLeaderboardListView
from quark.quote_board.views import QuoteListView
from quark.quote_board.views import SpeakerQuoteListView


urlpatterns = patterns(
    '',
    url(r'^$', QuoteListView.as_view(), name='list'),
    url(r'^(?P<quote_pk>\d+)/$', QuoteDetailView.as_view(), name='detail'),
    url(r'^add/$', QuoteCreateView.as_view(), name='add'),
    url(r'^leaderboard/$', QuoteLeaderboardListView.as_view(),
        name='leaderboard'),
    url(r'^speaker/(?P<user_id>\d+)/$', SpeakerQuoteListView.as_view(),
        name='speaker'),
)

quark/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^', include('quark.base.urls',
                      app_name='base')),
    url(r'^accounts/', include('quark.accounts.urls',
                               app_name='accounts',
                               namespace='accounts')),
    url(r'^achievements/', include('quark.achievements.urls',
                                   app_name='achievements',
                                   namespace='achievements')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^alumni/', include('quark.alumni.urls',
                             app_name='alumni',
                             namespace='alumni')),
    url(r'^candidates/', include('quark.candidates.urls',
                                 app_name='candidates',
                                 namespace='candidates')),
    url(r'^courses/', include('quark.courses.urls',
                              app_name='courses',
                              namespace='courses')),
    url(r'^email/', include('quark.emailer.urls',
                            app_name='emailer',
                            namespace='emailer')),
    url(r'^events/', include('quark.events.urls',
                             app_name='events',
                             namespace='events')),
    url(r'^exams/', include('quark.exams.urls',
                            app_name='exams',
                            namespace='exams')),
    url(r'^houses/', include('quark.houses.urls',
                             app_name='houses',
                             namespace='houses')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^industry/', include('quark.companies.urls',
                               app_name='companies',
                               namespace='companies')),
    url(r'^mailing-lists/', include('quark.mailing_lists.urls',
                                    app_name='mailing_lists',
                                    namespace='mailing-lists')),
    url(r'^minutes/', include('quark.minutes.urls',
                              app_name='minutes',
                              namespace='minutes')),
    url(r'^newsreel/', include('quark.newsreel.urls',
                               app_name='newsreel',
                               namespace='newsreel')),
    url(r'^notifications/', include('quark.notifications.urls',
                                    app_name='notifications',
                                    namespace='notifications')),
    url(r'^past-presidents/', include('quark.past_presidents.urls',
                                      app_name='past_presidents',
                                      namespace='past-presidents')),
    url(r'^profile/', include('quark.user_profiles.urls',
                              app_name='user_profiles',
                              namespace='user-profiles')),
    url(r'^project-reports/', include('quark.project_reports.urls',
                                      app_name='project_reports',
                                      namespace='project-reports')),
    url(r'^quote-board/', include('quark.quote_board.urls',
                                  app_name='quote_board',
                                  namespace='quote-board')),
    url(r'^resumes/', include('quark.resumes.urls',
                              app_name='resumes',
                              namespace='resumes')),
    url(r'^syllabi/', include('quark.syllabi.urls',
                              app_name='syllabi',
                              namespace='syllabi')),
    url(r'^videos/', include('quark.videos.urls',
                             app_name='videos',
                             namespace='videos')),
    url(r'^vote/', include('quark.vote.urls',
                           app_name='vote',
                           namespace='vote')),
)

# Add flatpages URLs
urlpatterns += patterns(
    'django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^about/contact/$', 'flatpage', {'url': '/about/contact/'},
        name='contact'),
    url(r'^about/eligibility/$', 'flatpage', {'url': '/about/eligibility/'},
        name='eligibility'),
    url(r'^people/committees/$', 'flatpage', {'url': '/people/committees/'},
        name='committees'),
    url(r'^student-resources/$', 'flatpage', {'url': '/student-resources/'},
        name='student-resources'),
    url(r'^resume-critique/$', 'flatpage', {'url': '/resume-critique/'},
        name='resume-critique'),
    url(r'^mock-interviews/$', 'flatpage', {'url': '/mock-interviews/'},
        name='mock-interviews'),
    url(r'^partnership_program/$', 'flatpage', {'url': '/partnership_program/'},
        name='partnership_program'),
)

# Handle page redirects
urlpatterns += patterns(
    '',
    url(r'^indrel/$', RedirectView.as_view(pattern_name='industry')),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quark/quote_board/models.py
from django.conf import settings
from django.db import models


class Quote(models.Model):
    quote = models.TextField(blank=False)
    speakers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      related_name='+')
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    time = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.quote

    class Meta(object):
        ordering = ('-time',)
        permissions = (
            ('view_quotes', 'Can view all quotes'),
        )

quark/quote_board/forms.py
from django import forms

from quark.quote_board.models import Quote
from quark.user_profiles.fields import UserCommonNameMultipleChoiceField


class QuoteForm(forms.ModelForm):
    speakers = UserCommonNameMultipleChoiceField()

    class Meta(object):
        model = Quote
        exclude = ('submitter',)

quark/quote_board/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from quark.quote_board.forms import QuoteForm
from quark.quote_board.models import Quote
from quark.shortcuts import create_leaderboard


class QuoteCreateView(CreateView):
    form_class = QuoteForm
    template_name = 'quote_board/add.html'

    @method_decorator(login_required)
    @method_decorator(
        permission_required('quote_board.add_quote', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(QuoteCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.submitter = self.request.user
        obj.save()
        return super(QuoteCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('quote-board:list')


class QuoteDetailView(DetailView):
    context_object_name = 'quote'
    model = Quote
    pk_url_kwarg = 'quote_pk'
    template_name = 'quote_board/detail.html'

    @method_decorator(login_required)
    @method_decorator(
        permission_required('quote_board.view_quotes', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(QuoteDetailView, self).dispatch(*args, **kwargs)


class QuoteLeaderboardListView(ListView):
    context_object_name = 'leader_list'
    template_name = 'quote_board/leaderboard.html'
    paginate_by = 50

    @method_decorator(login_required)
    @method_decorator(
        permission_required('quote_board.view_quotes', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(QuoteLeaderboardListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        # Get list of users who have been quoted
        speakers = Quote.objects.values_list('speakers')

        # Because quotes map to multiple users (speaker and submitter), use
        # extra to obtain the leaders ordered by number of times quoted
        querystring = 'SELECT COUNT(*) FROM quote_board_quote_speakers WHERE ' \
            'quote_board_quote_speakers.user_id = auth_user.id'

        leaders = get_user_model().objects.filter(id__in=speakers).extra(
            select={'score': querystring}).extra(
            order_by=['-score']).select_related('userprofile')

        return create_leaderboard(leaders, 70)


class QuoteListView(ListView):
    context_object_name = 'quote_list'
    queryset = Quote.objects.select_related(
        'submitter__userprofile').prefetch_related('speakers__userprofile')
    template_name = 'quote_board/list.html'

    @method_decorator(login_required)
    @method_decorator(
        permission_required('quote_board.view_quotes', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(QuoteListView, self).dispatch(*args, **kwargs)


class SpeakerQuoteListView(ListView):
    context_object_name = 'quote_list'
    display_user = None
    template_name = 'quote_board/speaker.html'

    @method_decorator(login_required)
    @method_decorator(
        permission_required('quote_board.view_quotes', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        self.display_user = get_object_or_404(
            get_user_model(), id=self.kwargs['user_id'])
        return super(SpeakerQuoteListView, self).dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = Quote.objects.filter(
            speakers__pk=self.kwargs['user_id']).select_related(
            'submitter__userprofile').prefetch_related('speakers__userprofile')

        return queryset

    def get_context_data(self, **kwargs):
        context = super(SpeakerQuoteListView, self).get_context_data(**kwargs)
        context['display_user'] = self.display_user
        context['num_quotes'] = context['quote_list'].count()

        return context

quark/quote_board/templates/quote_board/_quote_detail.html
{% load markup %}

<div class="entry">
  <div class="speakers">
    On {% if show_link %}
      <a href="{% url 'quote-board:detail' quote.pk %}">{{ quote.time }}</a>
    {% else %}
      {{ quote.time }}
    {% endif %},
    {% for speaker in quote.speakers.all %}
      <a href="{% url 'quote-board:speaker' speaker.pk %}">{{ speaker.userprofile.get_common_name }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    said:
  </div>
  <div class="quote">{{ quote.quote|markdown }}</div>
  <div class="submitter">Submitted by {{ quote.submitter }} 
  (<a href="{% url 'user_profiles:detail' quote.submitter.username %}">{{ quote.submitter.userprofile.get_common_name }}</a>)</div>
</div>

quark/quote_board/templates/quote_board/add.html
{% extends 'base.html' %}

{% block title %}Add A Quote{% endblock title %}

{% block intro %}<h1>Add a Quote</h1>{% endblock intro %}

{% block content %}

<form method="post">
  {% csrf_token %}
  {% include '_form.html' %}
  <div>
    <input type="submit" value="Submit">
  </div>
</form>
{% endblock content %}

quark/quote_board/templates/quote_board/detail.html
{% extends 'base.html' %}

{% block title %}Quote Board{% endblock title %}

{% block intro %}
<p><a href="{% url 'quote_board:list' %}">&laquo; Quote Board</a></p>
<h1>Quote</h1>
{% endblock intro %}

{% block content %}

{% include 'quote_board/_quote_detail.html' %}

{% endblock content %}

quark/quote_board/templates/quote_board/leaderboard.html
{% extends 'base.html' %}

{% block title %}Quote Leaderboard{% endblock title %}

{% block intro %}
<p><a href="{% url 'quote_board:list' %}">&laquo; Quote Board</a></p>
<h1>Quote Leaderboard</h1>
{% endblock intro %}

{% block content %}

<ul class="leaderboard">
  {% for entry in leader_list %}
  <li>
    {# Spaceless to fix whitespace issues with inline-block css style #}
    {% spaceless %}
    <div class="name {% cycle 'odd' 'even' %}
      {% if entry.user == user %}self{% endif %}">
        {{ entry.rank }}. <a href="{% url 'quote-board:speaker' entry.user.id %}">{{ entry.user.userprofile.get_common_name }}</a>
    </div>
    <span class="score-container {% cycle 'odd' 'even' %}"
      style="width: {{ entry.factor }}%;">
      <span class="score">{{ entry.user.score }}</span>
    </span>
    {% endspaceless %}
  </li>
  {% empty %}
  <p>Nobody has any achievements yet! :(</p>
  {% endfor %}
</ul>

{% include '_pagination.html' %}

{% endblock content %}

quark/quote_board/templates/quote_board/list.html
{% extends 'base.html' %}

{% block title %}Quote Board{% endblock title %}

{% block intro %}
<h1>Quote Board</h1>
{% endblock intro %}

{% block content %}

<p>
  <a href="{% url 'quote-board:add' %}" class="btn"><i class="fa fa-plus" title="add"></i> Add Quote</a>
  <a href="{% url 'quote-board:leaderboard' %}" class="btn"><i class="fa fa-bar-chart-o"></i> Leaderboard</a>
</p>

{% for quote in quote_list %}
{% include 'quote_board/_quote_detail.html' with show_link=True %}
{% endfor %}

{% endblock content %}

quark/quote_board/templates/quote_board/speaker.html
{% extends 'base.html' %}

{% block title %}
{{ display_user.userprofile.get_common_name }}'s Quotes
{% endblock title %}

{% block intro %}
<p><a href="{% url 'quote_board:list' %}">&laquo; Quote Board</a></p>
<h1>
  <a href="{% url 'user-profiles:detail' display_user.username %}">{{ display_user.userprofile.get_common_name }}</a>'s Quotes</h1>

<h3>{{ num_quotes }} quote{{ num_quotes|pluralize }}</h3>
{% endblock intro %}

{% block content %}

{% for quote in quote_list %}
{% include 'quote_board/_quote_detail.html' with show_link=True %}
{% endfor %}

{% endblock content %}